### ISSUE TITLE
Add support for three number versions such as 1.7.10 in the supports array

### ISSUE THREAD

**Issue by RadiatedMonkey** [PathfindersMC/API#6]

**Comment by ethamitc** [comment]
The `supports` array is just strings, so this shouldn't be a database issue.

**Comment by RadiatedMonkey** [comment]
I know this isn't a DB issue, I made a regular expression that matches all the version numbers so we don't get random strings

**Comment by RadiatedMonkey** [comment]
Fixed in a7082bc
