### ISSUE TITLE
plugin.save() is not a function in plugin.func.js:26

### ISSUE THREAD

**Issue by RadiatedMonkey** [PathfindersMC/API#7]

**Comment by ethamitc** [comment]
Can I get the full error stack please?

**Comment by RadiatedMonkey** [comment]
![image](https://user-images.githubusercontent.com/44266876/85320573-920a6a80-b4c3-11ea-8818-214957e6f603.png)

**Comment by ethamitc** [comment]
Fixed in ef008e0
